### ISSUE TITLE
How to use Ansible vault to encrypt password

### ISSUE THREAD

**Issue by jswetzen** [Yannik/ansible-role-relaymail#12]
I was looking for an ssmtp role really, but since it’s insecure I’m much more interested in using this! When thinking security though, I’m considering how to store the password safely in the role that’s supposed to be pushed to a git repo.

Do you have any experience with Ansible vault and would it be possible to include an example in the README? I figured I’d just ask since being security orented it’s probably something you’ve done and pasting an example should be simple.

**Comment by Yannik** [comment]
Well, I personally agree that ansible vault or something similar is a good idea for storing passwords, however I do not personally have any experience in implementing it. In principal I'm not against including an example in the README, however, I don't know how much value it would have, as it would probably just be a generic ansible vault demo?

**Comment by jswetzen** [comment]
Ok, too bad you hadn’t tried it. I’m starting to look through the Ansible Vault docs now and you can encrypt everything from a variable to whole role files. An example of exactly the vault feature that’s relevant here would be useful to me at least. When I get the time to figure it out, you might get a PR :)
